name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build base image
      run: bash scripts/build-base-image.sh

    - name: Build nginx image
      run: bash scripts/build-nginx.sh

    - name: Build standalone image
      run: bash scripts/build-standalone.sh

    - name: Build static image
      run: bash scripts/build-static.sh

    - name: Push images to GHCR
      run: bash scripts/push-images.sh
